import React, { createContext, useContext, useState } from 'react';

const translations = {
  en: {
    topBar: {
      defaultTitle: 'GeneFlare',
    },
    nav: {
      home: 'HOME',
      health: 'HEALTH',
      research: 'RESEARCH',
      shield: 'SHIELD',
      aiAssistant: 'AI ASSISTANT',
      social: 'SOCIAL',
      me: 'ME',
    },
    social: {
      searchPlaceholder: 'Find circles, friends, or posts...',
      dailyStar: 'Daily Health Star',
      joined: 'JOINED',
      hoursAgo: '{{count}} HOURS AGO',
      insight: 'AI Recovery Insight',
      circles: 'MY CIRCLES',
      trending: 'TRENDING',
      tabs: {
        feed: 'Feed',
        circles: 'Circles',
        challenges: 'Challenges',
        ranking: 'Ranking'
      },
      aiRecommended: 'AI Recommended',
      precisionMatch: 'Precision Match',
      cardioMgmt: 'Cardiovascular Management',
      cardioMgmtDesc: 'Based on your recent heart rate variability and activity data.',
      sleepOpt: 'Sleep Optimization',
      sleepOptDesc: 'Join 150+ members improving REM cycles through collective data.',
      joinCircle: 'Join Circle',
      browseMore: 'Browse More Circles',
      earlyBird: 'Early Bird Challenge',
      earlyBirdDesc: 'Wake up before 6:30 AM for 21 consecutive days',
      joinNow: 'Join Now',
      popular: 'Popular Challenges',
      springPrep: 'Spring Marathon Prep',
      teamFatLoss: 'Team Fat Loss',
      stepsDaily: '10K Steps Daily',
      hot: 'Hot',
      team: 'Team',
      seasonal: 'Seasonal',
      comingSoon: 'Coming Soon',
      summerHydration: 'Summer Hydration',
      mindfulnessMonth: 'Mindfulness Month',
      notifyMe: 'Notify Me',
      participants: 'participants',
      days: 'days',
      starts: 'Starts',
      ranking: {
        steps: 'Steps',
        sleep: 'Sleep',
        checkin: 'Check-in',
        data: 'Data',
        friends: 'Friends',
        circles: 'Circles',
        global: 'Global',
        thisWeek: 'This Week',
        leaderboard: 'Step Count Leaderboard',
        rank: 'Rank',
        user: 'User',
        activity: 'Activity',
        viewAll: 'View All Participants',
      },
    },
    settings: {
      title: 'Settings',
      account: 'Account & Security',
      notifications: 'Notifications',
      preferences: 'Preferences',
      language: 'Language',
      langName: 'English',
      logout: 'Log Out',
      identityBinding: 'Identity Binding',
      verified: 'Verified',
      passwordPin: 'Password & PIN',
      biometricLogin: 'Biometric Login',
      faceId: 'Face ID',
      walletSecurity: 'Wallet Security',
      healthReminders: 'Health Reminders',
      socialUpdates: 'Social Updates',
      promotions: 'Promotions',
      darkMode: 'Dark Mode',
      fontSize: 'Font Size',
      medium: 'Medium',
      storageData: 'Storage & Data',
      clearCache: 'Clear Cache',
      appVersion: 'App Version',
      legal: 'Legal',
      termsOfService: 'Terms of Service',
      privacyPolicy: 'Privacy Policy',
      licenses: 'Licenses',
    },
    home: {
      steps: 'Steps',
      sleep: 'Sleep',
      heartRate: 'Heart Rate',
      stress: 'Stress',
      comp67: 'Data Completeness 67%',
      aiConsult: 'AI Consultation',
      startChat: 'Consult AI Assistant',
      tasks: "Today's Tasks",
      pending: 'PENDING',
      bloodGlucose: 'Blood Glucose Log',
      bloodPressure: 'Blood Pressure Log',
      hotActivities: 'Hot Activities',
      earlyRise: '21-Day Early Rise',
      participants1240: '1,240 Participants',
      stepPK: 'Step Count PK',
      dailyCompetition: 'Daily Competition',
      dataAssetZone: 'Data Asset Task Zone',
      paidTask: 'PAID TASK',
      hengruiMedicine: 'Hengrui Medicine',
      aiaInsurance: 'AIA Insurance',
      recordForStudy: 'Record reading for diagnostic study',
      dailyVitalsInsurance: 'Daily vitals for insurance health plan',
      bloodGlucoseCollection: 'Blood Glucose Data Collection',
      bloodGlucoseDesc: 'Provide 7-day persistent glucose readings for medical research on drug efficacy.',
      levelCertifiedPlus: 'Level: Certified Plus',
      bloodPressureMonitoring: 'Blood Pressure Monitoring',
      bloodPressureDesc: 'Daily logging for health insurance premium discounts and risk assessment.',
      weeklyProgress: 'Weekly Progress',
      joined: 'JOINED',
      perWeek: '/Week',
      sleepQualityAnalysis: 'Sleep Quality Analysis',
      sleepQualityDesc: 'Share wearable sleep duration and depth data for actuarial modeling research.',
      deviceSyncReq: 'Device Sync Required',
      activity: 'Activity',
      briskWalk: '30-min Brisk Walk',
      briskWalkDesc: '30 minutes brisk pace',
      wellness: 'Wellness',
      dailyHealthCheckin: 'Daily Health Check-in',
      recordVitals: 'Record your daily vitals',
      goldShieldLv3: 'Gold Shield · Level 3',
      accumulatedGEF: 'Accumulated 192 GEF',
      viewShieldStrategy: 'View Shield Strategy',
      shieldLevel: 'Level',
      shieldLevelValue: 'Shield 3 · Elite',
      estimatedCoverage: 'Estimated Coverage',
      daysProtected: 'Days Protected',
      dailyCost: 'Daily Cost',
      earnMore: 'Earn More',
      spend: 'Spend',
      aiDesc: '24/7 personalized medical insights powered by AI.',
      gef10: '10 GEF',
      shieldUplift: 'Shield Uplift',
      oncologyMatch: 'Oncology Match Score',
      didBound: 'DID Bound Data',
      mintableState: 'Current mintable state:',
      preQualified: 'packs pre-qualified',
      missingSignals: {
        familyHistory: 'Family history',
        genotypePanel: 'Genotype panel',
        wearableContinuity: 'Wearable continuity',
        bloodBiomarkers: 'Blood biomarkers',
        sleepArchitecture: 'Sleep architecture',
      },
      marquee: {
        signalRunway: 'Signal Runway',
        mintReadiness: 'Mint Readiness',
        biomarkers: 'Biomarkers',
        shieldUplift: 'Shield Uplift',
        oncologyMatch: 'Oncology Match',
        didBound: 'DID Bound',
      },
      sync: {
        live: 'Live Sync',
        connected: 'Connected',
        syncing: 'Syncing...',
        appleUpdated: 'Apple Health · Updated 2m ago',
        didVerified: 'DID Cloud · Verified',
      },
      sections: {
        hero: {
          tag: 'Health Asset Engine',
          title: 'Build\nresearch-grade\nhealth assets.',
          subtitle: 'Your logs, biomarkers, and continuity signals are assembled like a live asset runway, not a passive health diary.',
        },
        controlBoard: {
          title: 'Control Board',
          subtitle: 'Live Asset State',
          healthScore: 'Health Score',
          assetCompleteness: 'Asset Completeness',
          mintReadyPacks: 'Mint Ready Packs',
          shieldTier: 'Shield Tier',
        },
        researchNFT: {
          tag: 'Research NFT Progress',
          title: 'Your health data is becoming a mintable Research NFT.',
          desc: 'Daily syncs are assembling a structured package tied to your DID. The closer this runway gets to full signal density, the stronger your mint pricing and pool eligibility.',
          mintReadiness: 'Mint readiness',
          estValue: 'Est. Value',
          missingSignal: 'Missing Signal',
          completeAndMint: 'Complete And Mint',
        },
        aiEditor: {
          tag: 'AI Signal Editor',
          title: 'Complete your genotype panel to increase NFT pricing power.',
          pricingLift: 'Predicted pricing lift: +42 GEF at mint',
          nextAction: 'Next best action: upload family history and genotype summary',
          shieldBoost: 'Shield boost: contributes to Diamond review track',
        },
        shield: {
          tag: 'Shield Progress',
          title: 'Gold 3 today. Japan precision screening next.',
          status: 'Gold 3 today',
          nextStep: 'Japan precision screening next',
          requirement: 'Add 48 GEF plus one research authorization to move into Diamond review and unlock CAR-T consultation coordination.',
        },
        planSummary: {
          tag: 'Plan Summary',
          title: 'Health Plan',
          executingPrefix: 'executing challenges',
          institutionPrefix: 'institution plans',
          viewAll: 'View All Plans',
          executingTitle: 'Executing Challenges',
          institutionTitle: 'Institution Plans',
          expectedValue: 'Expected Value',
          recommendedJoin: 'Recommended Join',
          plansSuffix: 'plans',
          desc: 'Monitor your health trajectory across all personal and institutional dimensions.',
        }
      },
      research: {
        mintNFT: 'MINT RESEARCH NFT',
        reviewDID: 'REVIEW DIGITAL ID',
      },
      healthTasks: {
        sections: {
          research: 'Research Tasks',
          personal: 'Personal Task Queue',
        },
        planTitlePrefix: 'Plan: ',
        summaryDesc: 'Expected value accumulated from current executing and institution plans.',
        reward: 'Reward',
        completeTask: 'Complete Task',
        cta: {
          complete: 'Complete Task',
        },
        states: {
          toStart: 'PENDING',
          inProgress: 'IN PROGRESS',
          verifying: 'TO VERIFY',
          completed: 'COMPLETED',
        },
        items: {
          'sleep-window': {
            title: 'Tonight Sleep Window',
            detail: 'Start recording before 22:30 to complete your night recovery curve.',
            cue: 'Improve Sleep',
            cta: 'Start Tonight',
          },
          'daily-checkin': {
            title: 'Nutrition Balance Check',
            detail: '1 more water and 1 more healthy meal log needed for a complete nutrition track.',
            cue: 'Balance Nutrition',
            cta: 'Track Intake',
          },
          'brisk-walk': {
            title: '30-min Brisk Walk',
            detail: 'Improve vascular recovery and metabolic rhythm for higher continuity score.',
            cue: 'Improve Recovery',
            cta: 'Open Path',
          },
          'upload-glucose': {
            title: 'Upload continuous glucose readings',
            subtitle: 'Unlock a high-value diabetes intervention pool match.',
            sponsor: 'Novartis Metabolic Lab',
          },
          'log-bp-series': {
            title: 'Log 30-day blood pressure series',
            subtitle: 'Complete the signal needed for Research NFT mint readiness.',
            sponsor: 'Bayer Research',
          },
          'verify-recovery': {
            title: 'Verify Recovery Series',
            detail: 'AI detected a 5-day walking sequence. Confirm your recovery rhythm and submit it to the health protocol history.',
          },
          'hydration-streak': {
            title: 'Hydration Streak Closed',
            detail: 'Your 7-day hydration target is complete. This behavior signal will lift your baseline continuity score.',
          }
        },
        plans: {
          'sleep-repair-protocol': 'Sleep Repair Protocol',
          'cardio-recovery-loop': 'Cardio Recovery Loop',
          'institution-metabolic-reset': 'Metabolic Reset',
          'tokyo-longevity-observation': 'Longevity Observation',
          'bayer-vascular-signal-study': 'Vascular Signal Study',
        }
      }
    },
    profile: {
      myNfts: 'My NFTs',
      dataHub: 'DataHub',
      flameShield: 'Flame Shield',
      serviceMarket: 'Service Market',
      myAchievements: 'My Achievements',
      checkinCalendar: 'Check-in Calendar',
      taskHistory: 'Task History',
      inviteFriends: 'Invite Friends',
      achievementBadges: 'Achievement Badges',
      privacyControls: 'Privacy Controls',
      dataExport: 'Data Export',
      help: 'Help',
      about: 'About',
      myAssets: 'My Assets',
      walletDetails: 'Wallet Details',
      earnMore: 'Earn More',
      myLevel: 'My Level',
      advanced: 'Advanced',
      nova: 'Nova',
      vitality: 'Vitality',
      elite: 'Elite',
      master: 'Master',
      advancedBenefits: 'Advanced Benefits:',
      benefitsDesc: 'SPARK earning ×1.15 | 10% off service market',
      days: 'days',
      multiplier: 'Multiplier',
      goldShield3: 'Gold Shield · Shield 3',
      achievements12: '12 Achievements',
      todayPercent: '+12% today',
    },
    profileNfts: {
      title: 'My NFTs',
      identityCore: 'Identity Core',
      healthIdentityNFT: 'Health Identity NFT',
      clinicalRank: 'Clinical Precision Rank',
      xpProgress: 'XP Progress',
      dataNFTs: 'Data NFTs',
      viewArchive: 'View Archive',
      q1HealthPack: '2026 Q1 Health Pack',
      forSale: 'For Sale',
      mintNew: 'Mint New',
      goToDataHub: 'Go to DataHub',
      limitedEditions: 'Limited Editions',
      springMarathon: 'Spring Marathon',
      mintedApril2026: 'Minted April 2026',
      exclusiveDrop: 'Exclusive Drop',
      christmasExclusive: 'Christmas Exclusive',
      mintedDec2025: 'Minted Dec 2025',
      seasonPack: 'Season Pack',
      safeWork: 'Safe Work',
    },
    researchPage: {
      terminal: 'Mint Terminal',
      title: 'Mint your health asset into a Research NFT.',
      desc: 'This terminal turns structured health signals into callable research inventory tied to your DID. Minting opens access rewards and long-horizon contribution return flows.',
      researchValue: 'Research value',
      mintReady: 'MINT-READY',
      pools: 'POOLS',
      totalGef: 'Total GEF',
      returnWaterfall: 'Return Waterfall',
      returnTitle: 'How value moves after mint.',
      inventoryBoard: 'Inventory Board',
      inventoryTitle: 'Mint-ready Research NFT packs',
      viewArchive: 'View archive',
      enterVault: 'Enter Vault',
      dataScope: 'Data scope:',
      directions: 'Authorized directions:',
      projectedValue: 'Projected value',
      mintNow: 'MINT ASSET',
      liveMatchbook: 'Live Matchbook',
      matchbookTitle: 'Active research demand against your assets.',
      accelerationTitle: 'Match acceleration active',
      accelerationDesc: 'Your asset is being matched against active research demand.',
      refresh: 'Refresh',
      proofStream: 'Proof Stream Active',
      proofTitle: 'Every authorization is recorded, every return is traceable.',
      rewardStages: {
        mint: {
          name: 'Mint Reward',
          value: '+18 GEF',
          detail: 'Triggered when a data pack is minted into a Research NFT and anchored to your DID.',
        },
        access: {
          name: 'Access Reward',
          value: '+60 GEF',
          detail: 'Triggered when a research sponsor first authorizes access to your anonymized asset.',
        },
        contribution: {
          name: 'Contribution Return',
          value: 'Ongoing',
          detail: 'Triggered by repeat usage, milestone studies, or downstream commercialization return flows.',
        },
      },
      packs: {
        metabolic: {
          title: 'Metabolic Continuity Pack',
          signals: 'CGM 180d · meals · sleep recovery · family history',
          directions: 'Type 2 diabetes early intervention, anti-aging nutrition',
          status: 'Mint-ready',
          value: 'Projected 260 GEF / year',
        },
        cardio: {
          title: 'Cardio Resilience Pack',
          signals: 'BP 90d · HRV 6m · movement logs · blood biomarkers',
          directions: 'Hypertension adherence, preventive insurance models',
          status: 'Ready after one more upload',
          value: 'Projected 180 GEF / year',
        },
      },
      matches: {
        glycemic: {
          title: 'Novartis x MIT Glycemic Stability Model',
          reward: '100 GEF + long-term return',
          action: 'Authorize anonymously',
        },
        longevity: {
          title: 'Longevity Atlas Japan Cohort',
          reward: 'Need genotype panel to unlock',
          action: 'View missing indicators',
        },
      },
      proofLogs: {
        did: 'DID bound at mint: did:gef:0x1a2b...3c4d',
        pools: 'Authorized pools: metabolic, longevity, cardio-prevention',
        calls: '12 research calls logged with on-chain proof of contribution',
      },
      guidance: {
        title: 'What is Research NFT?',
        mainTitle: 'Start Your Data Asset Journey',
        mainDesc: 'Before minting health assets and earning rewards, you need to verify your Digital Identity (DID). This is the first step to ensure data authenticity and protect your privacy.',
        cta: 'Review DID & Verify',
        step1: { title: 'Privacy Encryption', desc: 'Your raw health data stays local, ensuring absolute privacy.' },
        step2: { title: 'Identity Ownership', desc: 'Bind assets to your DID via ZK-Flare protocol.' },
        step3: { title: 'Value Return', desc: 'Hold R-NFTs for rewards (GEF) from research contributions.' },
      },
      modal: {
        viewDetails: 'View Details',
        includedPoints: 'Included Data Points',
        protocolReady: 'ZK-Flare Protocol Ready',
        disclaimer: 'Your data is hashed via Zero-Knowledge Proofs (ZKP) during minting. The NFT serves as an ownership certificate without containing identifiable personal privacy.',
        confirmMint: 'Confirm and Mint',
      },
      details: {
        hrv: { label: 'Heart Rate Variability (HRV)', desc: 'Autonomic nervous system feedback (last 30 days)' },
        rhr: { label: 'Resting Heart Rate (RHR)', desc: 'BPM trends and baseline' },
        sleep: { label: 'Sleep Architecture', desc: 'Deep, Light, and REM sleep ratios' },
        metabolic: { label: 'Metabolic Efficiency', desc: 'Calculated based on steps and calorie burn' },
        spo2: { label: 'Oxygen Saturation (SpO2)', desc: 'Nightly blood oxygen monitoring' },
        load: { label: 'Exercise Load', desc: 'Cardio performance during high intensity' },
        recovery: { label: 'Recovery Index', desc: 'Heart rate drop speed post-exercise' },
      },
      mintNFT: 'MINT RESEARCH NFT',
      reviewDID: 'REVIEW MY DID',
      faq: {
        title: 'Learn more about Research',
        whatIs: {
          title: 'What is Research NFT?',
          desc: 'A secure, encrypted container that represents your structured health assets on-chain.'
        },
        privacy: {
          title: 'Privacy & Security',
          desc: 'Data is anonymized via ZK-Proofs. Your real identity is never exposed to researchers.'
        },
        control: {
          title: 'Full Ownership',
          desc: 'You can revoke access or delete your asset anytime. You own the private keys to your data.'
        }
      },
    },
    profileShield: {
      title: 'Flame Shield',
      mutualAidProtocol: 'Mutual Aid Protocol',
      mutualAidDesc: 'By contributing GEF continuously, you join a global mutual aid pool. This community-driven protocol ensures that when any member faces a major health challenge, the collective resources of the pool provide comprehensive medical and financial assistance.',
      activeShieldStatus: 'Active Shield Status',
      goldTierSecurity: 'Gold Tier Security',
      monthsActive: 'Months Active',
      totalCredit: 'Total Credit',
      thisMonth: 'This Month',
      platformMatch: 'Platform Match',
      progressToDiamond: 'Progress to Diamond',
      bronze: 'Bronze',
      silver: 'Silver',
      gold: 'Gold',
      diamond: 'Diamond',
      legend: 'Legend',
      upgradeToDiamond: 'Upgrade to Diamond Requires',
      userLv5: 'User Level 5',
      guaranteedProtection: 'Guaranteed Protection',
      viewAll: 'View All',
      japanesePrecisionCheck: 'Japanese Precision Checkup',
      stemCellStorage: 'Stem Cell Storage',
      prpTherapy: 'PRP Regeneration Therapy',
      estimatedPrice1: 'Est. ¥350,000-¥560,000',
      estimatedPrice2: 'Est. ¥210,000-¥420,000',
      estimatedPrice3: 'Est. ¥140,000-¥280,000',
      diamondExclusive: 'Upgrade to Diamond Shield to unlock these services',
      requiresLevel5: 'Requires User Level 5',
      nkCell: 'NK Cell Immunotherapy \u2014 200k-500k JPY',
      protonTherapy: 'Proton/Heavy Ion Referral \u2014 400k-800k JPY',
      howToUpgrade: 'How to Upgrade',
      upgradeShield: 'Upgrade Shield',
      redemptionHistory: 'Redemption History',
      planDetails: 'Plan Details',
    },
    shieldPage: {
      title: 'Flame Shield',
      vip: 'VIP',
      heroTitle: 'Exclusive access. Elite coordination.',
      heroDesc: 'Your health asset contribution has unlocked the Gold tier. Access Japan-led care coordination and high-end treatment pathways.',
      currentTier: 'Current tier',
      mutualPool: 'Mutual Pool',
      benefitScore: 'Benefit score',
      unlocked: 'Unlocked',
      perks: '4 perks',
      tierPathway: 'Tier pathway',
      diamondProgress: '72% to Diamond',
      privilegeRunway: 'Privilege Runway',
      runwayTitle: 'Contribution & continuity unlock premium access.',
      privilegeServices: 'Privilege Services',
      eliteDirectory: 'Elite Care Directory',
      required: 'Required',
      paymentMethod: 'Payment Method',
      reserveAccess: 'Reserve Access',
      locked: 'Locked',
      upgradeActions: {
        deposit: 'Deposit 48 more GEF into Mutual Pool',
        authorize: 'Authorize one new oncology-grade Research NFT',
        continuity: 'Maintain 90-day continuity on wearable and blood marker data',
      },
      runwayPoints: {
        quality: 'Research-grade data quality increases your tier eligibility.',
        deposits: 'GEF deposits expand the mutual pool and your privilege ceiling.',
        review: 'AI-assisted review speeds coordination instead of promising outcomes.',
      },
      services: {
        screening: {
          tier: 'Gold 3',
          title: 'Japan precision screening coordination',
          payment: 'Pay with GEF or Shield credits',
          detail: 'Tokyo checkup routing, bilingual case prep, and post-screening review support.',
        },
        cart: {
          tier: 'Diamond',
          title: 'CAR-T & proton therapy guidance',
          payment: 'GEF + SPARK blended redemption',
          detail: 'Eligibility preparation, cross-border care coordination, and expert second-opinion access.',
        },
        regenerative: {
          tier: 'Legend',
          title: 'Regenerative medicine concierge',
          payment: 'Shield tier priority access',
          detail: 'Japan-based stem cell, anti-aging, and advanced recovery pathway coordination.',
        },
      },
    },
    profilePrivacy: {
      title: 'Privacy Controls',
      desc: 'Control how your health data is used. You have full ownership of all your data on-chain.',
      wearableData: 'Wearable Data',
      wearableDesc: 'Heart rate, steps, sleep, activity data',
      physicalExam: 'Physical Exam',
      physicalExamDesc: 'Blood tests, imaging, clinical assessments',
      questionnaireData: 'Questionnaire Data',
      questionnaireDesc: 'Health surveys, lifestyle assessments',
      geneticData: 'Genetic Data',
      geneticDesc: 'Genomic analysis, hereditary markers',
      aiAnalysis: 'AI Analysis',
      anonymousAggregate: 'Anonymous Aggregate',
      tradeable: 'Tradeable',
      globalMgmt: 'Global Management',
      disableTrading: 'Disable All Data Trading',
      disableAggregation: 'Disable All Aggregation',
      exportAll: 'Export All My Data',
      deleteAccount: 'Delete Account & Data',
    },
    quickActions: {
      title: 'Quick Actions',
      healthCheckin: 'Health Check-in',
      uploadReport: 'Upload Report',
      recordData: 'Record Data',
      recordDiet: 'Record Diet',
      medicationLog: 'Medication Log',
      fillQuestionnaire: 'Questionnaire',
      collapse: 'Collapse',
      aiConsultation: 'AI Consultation',
      startDiagnostic: 'Start professional diagnostic support',
      pending: 'Pending',
      pendingItems: 'Pending items',
    },
    ai: {
      closeTitle: 'Close conversation',
      closeLabel: 'Close conversation and return',
      greeting: "Hi there! I'm your GeneFlare AI assistant. I've analyzed your latest biological age markers (currently at 28). How can I support your health journey today?",
      intro: "You can ask me to interpret medical reports, give personalized health plans, or log your daily vitals directly.",
      inputPlaceholder: 'Describe your symptoms or ask for a report analysis...',
      tapToUpload: 'Tap to upload file',
      checkinText: 'I want to do my daily health check-in.',
      uploadText: 'I have a new health report. Can you interpret it for me?',
      dataText: 'I need to record my blood pressure / glucose levels.',
      dietText: 'Log my meal for today.',
      medsText: 'Record my medication intake.',
      surveyText: 'Show me any pending health questionnaires.',
      respDefault: "I'm processing that for you. Is there anything specific you'd like me to focus on?",
      respUpload: "Understood. Please upload your report (PDF or Image). I will analyze the metrics across 12 organ systems and provide a biological age impact assessment.",
      respCheckin: "Great! Let's start your 60-second health check-in. How has your energy level been today on a scale of 1-10?",
      respData: "Ready to record. Would you like to log your Blood Pressure, Glucose, or Heart Rate?",
      respDiet: "I've opened your diet journal. You can describe your meal or snap a photo of it for calorie and macro estimation.",
    },
    health: {
      title: 'Health Data',
      tabs: {
        overview: 'Overview',
        data: 'Data',
        assessment: 'Assessment',
        plan: 'Plan',
        report: 'Report',
      },
      twinTitle: 'Digital Twin Visualization',
      integrity: 'Integrity',
      status: {
        normal: 'Normal',
        attention: 'Attention',
        risk: 'Risk',
      },
      coreMetrics: 'Core Metrics',
      devices: {
        appleHealth: 'Apple Health',
        googleFit: 'Google Fit',
        geniusRing: 'Genius Smart Ring',
        smartFabric: 'Smart Fabric',
      },
      manageMetrics: 'Manage Metrics',
      bp: 'BP',
      sugar: 'Sugar',
      organScores: 'Organ System Scores',
      detailedAnalysis: 'Detailed Analysis',
      radarLabel: {
        cardio: 'Cardio',
        resp: 'Resp',
        dig: 'Dig',
        meta: 'Meta',
        musc: 'Musc',
        imm: 'Imm',
      },
      radarLegend: {
        optimal: 'Optimal',
        attention: 'Attention',
        risk: 'Risk',
        current: 'Current Vitality',
      },
      bioAge: {
        peak: 'Peak Vitality Achieved',
        age: 'Age',
        ageLabel: 'Your Biological Age',
        desc: "You're performing at the level of someone 7 years younger. Metabolic efficiency is optimized for peak performance.",
      },
      alerts: 'AI Health Alerts',
      viewAll: 'View All',
      alertMetabolic: 'Metabolic markers rising for 3 months',
      alertMetabolicDesc: 'Early indicators suggest a shift in insulin sensitivity. Consider reducing glucose spikes.',
      alertSleep: "Sleep HRV is low, this week's trend",
      alertSleepDesc: 'Your recovery score has dropped 15% since Monday. Prioritize restorative rest tonight.',
      dataSources: 'Data Sources',
      connected: 'CONNECTED',
      disconnected: 'DISCONNECTED',
      dataCompleteness: 'Data Completeness',
      healthTimeline: 'Health Data Timeline',
      loadMore: 'Load more...',
      assetCompleteness: {
        currentIntegrity: 'Current Integrity',
        heroDesc: 'Your health assets are nearing research-grade density. Complete more logs to unlock premium insights.',
        manageAll: 'Manage All',
        signalDensity: 'Signal Density Breakdown',
        aiAnalysis: 'AI Signal Analysis',
        mintResearchNFT: 'Mint Research NFT',
        addSource: 'Add data source',
        sourceDesc: {
          dailySync: 'Daily sync active',
          ready: 'Ready for analysis',
          connect: 'Tap to connect',
        },
        timeline: {
          autoSync: 'Auto sync',
          autoSyncDetail: 'HR 72 · Steps 3,240',
          sleepData: 'Sleep data',
          sleepDataDetail: 'Duration 7h 12m · Deep 1h 45m',
          manualEntry: 'Manual entry',
          manualEntryDetail: 'Blood Pressure 118/76',
          uploadedReport: 'Uploaded exam report',
          uploadedReportDetail: 'AI analysis complete',
          questionnaire: 'Quarterly health questionnaire',
          questionnaireDetail: 'Completed',
          today: 'Today 10:32',
          yesterday: 'Yesterday 22:15',
          mar28: 'Mar 28',
          mar25: 'Mar 25',
          mar15: 'Mar 15',
        },
      },
      tags: {
        wearable: 'Wearable Data',
        questionnaire: 'Questionnaire',
        physicalExam: 'Physical Exam',
        medLog: 'Medication Log',
        genetics: 'Genetics',
        diet: 'Diet Journal',
      },
      medicationAd: 'Complete medication records to unlock advanced drug interaction analysis powered by GeneFlare AI.',
      riskFactors: 'My Health Risk Factors',
      analysisDate: 'Analysis: 08 Oct',
      highRisk: 'High Risk',
      caution: 'Caution',
      lowRisk: 'Low Risk',
      fbs: 'Fasting Blood Sugar',
      fbsDesc: 'Elevated glucose levels detected. Immediate clinical review recommended.',
      sleepHRV: 'Sleep HRV',
      bmiOverweight: 'BMI Overweight',
      vitD: 'Vitamin D',
      vitDDesc: 'Sufficient levels maintained',
      availableAssessments: 'Available Assessments',
      aiReady: 'AI ENGINE READY',
      assessProfile: 'Comprehensive Profile',
      assessProfileDesc: 'Full molecular & genomic scan',
      assessCardio: 'Cardiovascular Risk',
      assessCardioDesc: 'Arterial age & lipid panel',
      assessMeta: 'Metabolic Health',
      assessMetaDesc: 'Glucose response & insulin',
      assessBioAge: 'Biological Age',
      assessBioAgeDesc: 'Epigenetic clock analysis',
      estResult: 'Est. 48h result',
      realtimeSync: 'Real-time sync',
      historicalReports: 'Historical Reports',
      digitalTwinInfo: 'Generate a predictive AI model of your biology on the blockchain.',
      initiateSync: 'INITIATE SYNC',
      activePlans: 'Active Health Plans',
      targetRisks: 'Targeting Risks',
      healthBenefits: 'Health Benefits',
      aiRecPlan: 'AI Recommended Plan',
      aiRecBody: 'Based on your recent HRV data, a Mindfulness & Breathwork protocol is suggested to lower evening stress.',
      reviewProtocol: 'Review Protocol',
      effectTracking: 'Effectiveness Tracking',
      restingHR: 'RESTING HR',
      dailySteps: 'DAILY STEPS',
      deepSleep: 'DEEP SLEEP',
      completedPlans: 'Completed Plans',
      monthlyReport: 'Monthly Report',
      compReview: 'Comprehensive Review',
      examAnalysis: 'Physical Exam Analysis',
      bioDetected: '12 Biomarkers Detected',
      precisionAI: 'Precision AI Assessment',
      stabilityIndex: 'Stability Index: 98%',
      mintTitle: 'Mint Health Data NFT',
      mintDesc: 'Secure your health reports on-chain and earn sovereign rewards.',
      mintReq: 'Requires LV.4+',
      unlockMint: 'Unlock Minting Feature',
      aiGenerated: 'AI GENERATED',
      verified: 'VERIFIED',
      lowRiskBadge: 'LOW RISK',
    },
    healthPlan: {
      dashboard: {
        pageTitle: 'All Plans',
        tag: 'Plan Dashboard',
        title: 'Turn every task into a plan with a clear owner.',
        desc: 'Health plans, institution plans, and every attached task now run in one dashboard. You can see what is executing, what is recommended, and which institution plans are worth joining next.',
        executingPlans: 'Executing plans',
        todayTasks: 'Today tasks',
        recommendedPlans: 'Recommended plans',
        institutionPlans: 'Institution plans',
      },
      executing: 'Executing Plans',
      recommended: 'Recommended Plans',
      institution: 'Institution Plans',
      effectTracking: 'Effect Tracking',
      completed: 'Completed Plans',
      activeNow: 'Active now',
      researchLinked: 'Research linked',
      taskStates: 'Task States',
      planQueue: 'Plan Task Queue',
      mixedStatus: 'Mixed Status',
      planValue: 'Plan value',
      todayTask: 'Today task',
      reward: 'Plan reward',
      completedPlansMap: {
        'hydration-challenge': 'Hydration Challenge',
        'intermittent-fasting-intro': 'Intermittent Fasting Intro',
      },
    },
    healthScorePage: {
      title: 'Health Assessment',
      overallScore: 'Overall Health Score',
      gradeLabel: 'Above Average · Excellent',
      scoreDesc: 'Your overall health is in good condition. 1 high-risk factor and 2 caution items require attention.',
      riskEntry: 'Health Risk Factors',
      poor: 'Poor',
      fair: 'Fair',
      good: 'Good',
      excellent: 'Excellent',
    },
    shieldLayout: {
      tabsLabel: 'Runway Tabs',
      home: 'Shield Home',
      services: 'Services',
    },
    shieldServices: {
      premium: 'Premium Services',
      title: 'Global Care\nNetwork.',
      desc: 'Exclusive medical access and bespoke longevity treatments curated for Flame Shield members.',
      payment: 'Payment',
      services: {
        jpCheckup: {
          title: 'Japan precision checkup package',
          category: 'Diagnostic',
          payment: 'Pay with GEF or Shield credits',
          detail: 'High-resolution imaging, comprehensive blood markers, bilingual translation support, and guided follow-up review by top Tokyo clinicians.',
          tags: {
            petct: 'PET-CT',
            biomarkers: 'Biomarkers',
            vipRouting: 'VIP Routing',
          },
        },
        longevity: {
          title: 'Longevity intervention planning',
          category: 'Regenerative',
          payment: 'GEF + SPARK blended redemption',
          detail: 'Anti-aging coaching, comprehensive epigenetic biomarker reviews, and premium clinic coordination for cellular optimization.',
          tags: {
            antiAging: 'Anti-aging',
            stemCell: 'Stem Cell',
            coaching: 'Coaching',
          },
        },
        referral: {
          title: 'Cross-border expert referral',
          category: 'Consultation',
          payment: 'Shield tier priority access',
          detail: 'Expert second opinion routing for oncology, rare diseases, and advanced therapies from world-renowned specialists.',
          tags: {
            oncology: 'Oncology',
            secondOpinion: 'Second Opinion',
            fastTrack: 'Fast-track',
          },
        },
      },
    },
    collectionPage: {
      title: 'Data Vault',
      tag: 'Secure Asset Repository',
      heading: 'My Collection',
      vaultNetWorth: 'Vault Net Worth',
      annualApr: 'Annual APR',
      tier: 'Tier',
      active: 'Active',
      totalYield: 'Total Yield',
      integrity: 'Integrity',
      assets: {
        metabolic: 'Metabolic Matrix',
        cardio: 'Cardio Rhythm',
        neuro: 'Neuro Pattern',
      },
    },
    plansData: {
      'sleep-repair-protocol': {
        sourceLabel: 'Personal Protocol',
        progressLabel: 'Day 6 / 14',
        summary: 'Rebuild night recovery stability and generate a cleaner fatigue-risk history for Shield review.',
        recommendationReason: 'Your recent sleep continuity dropped below target, so this protocol has the highest near-term uplift.',
        todayAction: 'Start tonight sleep window before 22:30.',
        planValue: 'Sleep recovery proof +1',
      },
      'cardio-recovery-loop': {
        sourceLabel: 'Personal Protocol',
        progressLabel: '3 tasks live',
        summary: 'Keep vascular recovery, movement rhythm, and hydration behavior inside one consistent weekly loop.',
        recommendationReason: 'You already have enough step and heart-rate data to turn this into a continuity-driven plan.',
        todayAction: 'Validate your five most recent brisk-walk records.',
        planValue: 'Recovery continuity +18',
      },
      'institution-metabolic-reset': {
        sourceLabel: 'Novartis Metabolic Lab',
        progressLabel: 'Open for join',
        summary: 'A research-backed metabolic reset plan using glucose continuity, nutrition timing, and intervention readiness.',
        recommendationReason: 'Your recent glucose uploads and nutrition logs already match 68% of the required baseline.',
        todayAction: 'Upload the last 7 days of continuous glucose readings.',
        planValue: 'Research eligibility +1',
        participants: '240 seats',
        duration: '14 days',
        progress: 'Baseline 68% match',
        tag: 'AI recommended',
      },
      'tokyo-longevity-observation': {
        sourceLabel: 'Tokyo Precision Health Network',
        progressLabel: '2 cohorts left',
        summary: 'Join a Japan-linked observation plan focused on sleep, wearable continuity, and longevity biomarker pairing.',
        recommendationReason: 'Your current sleep and recovery history makes you a strong candidate for the next intake window.',
        todayAction: 'Bind 14-day wearable continuity and fasting biomarker summary.',
        planValue: 'Japan cohort review',
        participants: '128 seats',
        duration: '21 days',
        progress: 'Cohort open',
        tag: 'Japan cohort',
      },
      'bayer-vascular-signal-study': {
        sourceLabel: 'Bayer Research',
        progressLabel: 'Recruiting now',
        summary: 'A structured blood-pressure and vascular adherence plan designed for longitudinal signal capture.',
        recommendationReason: 'Your blood-pressure history is already close to mint-grade and can be upgraded by one committed plan.',
        todayAction: 'Log 30-day blood pressure series.',
        planValue: 'Vascular signal pack',
        participants: '180 seats',
        duration: '30 days',
        progress: 'Signal capture',
        tag: 'Mint linked',
      },
    },
    profilePage: {
      controlCenter: 'Control Center',
      title: 'Your Web3 Health Identity',
      desc: 'The cryptographic core of your Research NFT assets and Flame Shield benefits. Own your data, route securely.',
      primaryDid: 'Primary DID',
      nodeRouting: 'Node Routing',
      singaporeNode: 'Singapore Global IP',
      behaviorRewards: 'Behavior Rewards',
      thisWeek: '+450 this week',
      settlementShield: 'Settlement & Shield',
      gefDesc: 'Core governance token for Shield upgrades.',
      stakeGef: 'Stake GEF',
      rToken: 'R-Token',
      activeProjects: '3 Projects',
      activeProjectsDesc: 'Special research rights currently active.',
      authorizationCenter: 'Authorization Center',
      authorizationDesc: 'Manage 4 active research permissions, disable ad usage, and export your permission log.',
      privacy: 'Privacy',
      privacyDesc: 'Adjust research permissions & export data ledger.',
      preferences: 'Preferences',
      preferencesDesc: 'Security, language, notifications, and wallet.',
      researchAssets: 'Research Assets',
      dataVault: 'Data Vault',
      dataVaultDesc: 'Explore your collection of verified health NFTs.',
    },
    mintWorkflow: {
      scanning: "Scanning Signals",
      scanningDetail: "Aggregating biometrics...",
      encrypting: "DID Encryption",
      encryptingDetail: "Securing ZK-Proofs...",
      finalizing: "Finalizing Block",
      finalizingDetail: "Committing to Ledger...",
      success: "MINT SUCCESSFUL",
      successDetail: "Your health asset is now yielding research rewards.",
      inventory: "View in Inventory",
      metadata: {
        authenticated: "Authenticated Asset",
        integrity: "Data Integrity",
        reward: "Reward Pool",
        disclaimer: "This certificate proves that biometrical data has been processed via ZK-Flare protocol and committed to the research ledger."
      }
    }
  },
  zh: {
    home: {
      steps: '步数',
      sleep: '睡眠',
      heartRate: '心率',
      stress: '压力值',
      comp67: '数据完整度 67%',
      aiConsult: 'AI 咨询',
      startChat: '咨询 AI 助手',
      tasks: '今日任务',
      pending: '待处理',
      bloodGlucose: '血糖记录',
      bloodPressure: '血压记录',
      hotActivities: '热门活动',
      earlyRise: '21天早起挑战',
      participants1240: '1,240 人参与',
      stepPK: '步数PK',
      dailyCompetition: '每日竞赛',
      dataAssetZone: '数据资产任务区',
      paidTask: '有偿任务',
      hengruiMedicine: '恒瑞医药',
      aiaInsurance: '友邦保险',
      recordForStudy: '为诊断研究记录读数',
      dailyVitalsInsurance: '每日体征数据 · 保险健康计划',
      bloodGlucoseCollection: '血糖数据采集',
      bloodGlucoseDesc: '提供连续 7 天的持续血糖读数，用于药物疗效医学研究。',
      levelCertifiedPlus: '等级: 认证 Plus',
      bloodPressureMonitoring: '血压监测',
      bloodPressureDesc: '每日记录，用于健康保险优惠及风险评估。',
      weeklyProgress: '本周进度',
      joined: '已加入',
      perWeek: '/周',
      sleepQualityAnalysis: '睡眠质量分析',
      sleepQualityDesc: '分享穿戴设备的睡眠时长和深度数据，用于精算建模研究。',
      deviceSyncReq: '需要设备同步',
      activity: '运动',
      briskWalk: '30分钟快走',
      briskWalkDesc: '30 分钟快走',
      wellness: '健康',
      dailyHealthCheckin: '每日健康打卡',
      recordVitals: '记录您的每日体征',
      goldShieldLv3: '黄金盾 · 等级 3',
      accumulatedGEF: '累计 192 GEF',
      viewShieldStrategy: '查看护盾策略',
      shieldLevel: '等级',
      shieldLevelValue: '盾牌 3 · 精英',
      estimatedCoverage: '预估保障',
      daysProtected: '保障天数',
      dailyCost: '每日消耗',
      earnMore: '赚取更多',
      spend: '去消费',
      aiDesc: '7×24 小时 AI 驱动的个性化医疗洞察。',
      gef10: '10 GEF',
      shieldUplift: 'Shield 加固',
      oncologyMatch: '肿瘤匹配评分',
      didBound: 'DID 绑定数据',
      mintableState: '当前可铸造状态：',
      preQualified: '个数据包已预审',
      missingSignals: {
        familyHistory: '家族病史',
        genotypePanel: '基因型面板',
        wearableContinuity: '穿戴连续性',
        bloodBiomarkers: '血液生物标志物',
        sleepArchitecture: '睡眠架构',
      },
      marquee: {
        signalRunway: '信号跑道',
        mintReadiness: '铸造准备',
        biomarkers: '生物标志物',
        shieldUplift: 'Shield 提升',
        oncologyMatch: '肿瘤匹配',
        didBound: 'DID 绑定',
      },
      sync: {
        live: '实时同步',
        connected: '已连接',
        syncing: '同步中...',
        appleUpdated: 'Apple Health · 2 分钟前更新',
        didVerified: 'DID 云端 · 已验证',
      },
      sections: {
        hero: {
          tag: '健康资产引擎',
          title: '构建\n科研级\n健康资产。',
          subtitle: '您的日志、生物标志物和连续性信号正像实时资产跑道一样被组装，而不仅仅是被动的健康日记。',
        },
        controlBoard: {
          title: '控制面板',
          subtitle: '实时资产状态',
          healthScore: '健康评分',
          assetCompleteness: '资产完整度',
          mintReadyPacks: '待铸造数据包',
          shieldTier: 'Shield 等级',
        },
        researchNFT: {
          tag: '科研 NFT 进度',
          title: '您的健康数据正在成为可铸造的科研 NFT。',
          desc: '每日同步正在组装绑定到您 DID 的结构化数据包。该跑道越接近全信号密度，您的铸造定价和池准入资格就越强。',
          mintReadiness: '铸造准备就绪',
          estValue: '预估价值',
          missingSignal: '缺失信号',
          completeAndMint: '完成并铸造',
        },
        aiEditor: {
          tag: 'AI 信号编辑器',
          title: '完成您的基因型面板以提高 NFT 定价权。',
          pricingLift: '预计定价提升：铸造时 +42 GEF',
          nextAction: '下一步最佳行动：上传家族史和基因型摘要',
          shieldBoost: 'Shield 加成：有助于进入钻石评审轨道',
        },
        shield: {
          tag: 'Shield 进度',
          title: '今日 Gold 3。下一步：日本精密筛查。',
          status: '今日 Gold 3',
          nextStep: '下一步：日本精密筛查',
          requirement: '添加 48 GEF 以及一项科研授权，即可进入钻石评审并解锁 CAR-T 咨询协调。',
        },
        planSummary: {
          tag: '计划概览',
          title: '健康计划',
          executingPrefix: '项执行中挑战',
          institutionPrefix: '项机构计划',
          viewAll: '查看所有计划',
          executingTitle: '执行中挑战',
          institutionTitle: '机构计划',
          expectedValue: '预期价值',
          recommendedJoin: '推荐加入',
          plansSuffix: '项计划',
          desc: '从个人和机构维度全面监控您的健康轨迹。',
        }
      },
      research: {
        mintNFT: '资产打包',
        reviewDID: '身份档案',
      },
      healthTasks: {
        sections: {
          research: '科研任务',
          personal: '个人任务队列',
        },
        planTitlePrefix: '所属计划 · ',
        summaryDesc: '当前执行计划与机构计划可累计获得的阶段价值。',
        reward: '奖励',
        completeTask: '完成任务',
        cta: {
          complete: '完成任务',
        },
        states: {
          toStart: '待开始',
          inProgress: '进行中',
          verifying: '待验证',
          completed: '已完成',
        },
        items: {
          'sleep-window': {
            title: '今晚睡眠窗口',
            detail: '在今晚 22:30 前开启睡眠窗口记录，补充夜间恢复曲线。',
            cue: '提升睡眠质量',
            cta: '今晚开始',
          },
          'daily-checkin': {
            title: '营养平衡检查',
            detail: '今天还差 1 次饮水和 1 次轻食记录，即可形成完整营养轨迹。',
            cue: '提升均衡营养',
            cta: '记录摄入',
          },
          'brisk-walk': {
            title: '30分钟快走',
            detail: '改善血管恢复与代谢节奏，推动你的连续性评分进入更高区间。',
            cue: '提升恢复能力',
            cta: '开启路径',
          },
          'upload-glucose': {
            title: '上传连续血糖读数',
            subtitle: '解锁高价值糖尿病干预池匹配。',
            sponsor: '诺华代谢实验室',
          },
          'log-bp-series': {
            title: '记录 30 天血压序列',
            subtitle: '完成科研 NFT 铸造就绪所需的信号。',
            sponsor: '拜耳研究中心',
          },
          'verify-recovery': {
            title: '验证恢复序列',
            detail: 'AI 已检测到 5 日步行序列，请确认恢复节奏并提交至健康协议历史。',
          },
          'hydration-streak': {
            title: '饮水连续性已完成',
            detail: '连续 7 天饮水目标已达成，这段行为信号将抬升你的基础连续性评分。',
          }
        },
        plans: {
          'sleep-repair-protocol': '睡眠修复方案',
          'cardio-recovery-loop': '心血管恢复循环',
          'institution-metabolic-reset': '代谢重置计划',
          'tokyo-longevity-observation': '东京长寿观察',
          'bayer-vascular-signal-study': '拜耳血管信号研究',
        }
      }
    },
    topBar: {
      defaultTitle: 'GeneFlare',
    },
    nav: {
      home: '首页',
      health: '健康',
      research: '研究',
      shield: 'Shield',
      aiAssistant: 'AI 助手',
      social: '社交',
      me: '我的',
    },
    profile: {
      myNfts: '我的 NFT',
      dataHub: '数据中心',
      flameShield: '火焰盾',
      serviceMarket: '服务市场',
      myAchievements: '我的成就',
      checkinCalendar: '签到日历',
      taskHistory: '任务历史',
      inviteFriends: '邀请好友',
      achievementBadges: '成就徽章',
      privacyControls: '隐私控制',
      dataExport: '数据导出',
      help: '帮助中心',
      about: '关于',
      myAssets: '我的资产',
      walletDetails: '钱包详情',
      earnMore: '赚取更多',
      myLevel: '我的等级',
      advanced: '进阶',
      nova: '新星',
      vitality: '活力',
      elite: '精英',
      master: '大师',
      advancedBenefits: '进阶权益:',
      benefitsDesc: 'SPARK 收益 ×1.15 | 服务市场享 9 折',
      days: '天',
      multiplier: '倍率',
      goldShield3: '黄金盾 · 盾牌 3',
      achievements12: '12 项成就',
      todayPercent: '今日 +12%',
    },
    profileNfts: {
      title: '我的 NFT',
      identityCore: '身份核心',
      healthIdentityNFT: '健康身份 NFT',
      clinicalRank: '临床精准等级',
      xpProgress: '经验进度',
      dataNFTs: '数据 NFT',
      viewArchive: '查看归档',
      q1HealthPack: '2026 Q1 健康包',
      forSale: '可出售',
      mintNew: '铸造新 NFT',
      goToDataHub: '前往数据中心',
      limitedEditions: '限量版',
      springMarathon: '春季马拉松',
      mintedApril2026: '铸造于 2026年4月',
      exclusiveDrop: '独家发行',
      christmasExclusive: '圣诞限定',
      mintedDec2025: '铸造于 2025年12月',
      seasonPack: '季节套装',
      safeWork: '安全作品',
    },
    researchPage: {
      terminal: '铸造终端',
      title: '将你的健康资产铸造为 Research NFT。',
      desc: '该终端会把结构化健康信号转化为绑定 DID 的科研可调用资产。铸造后可开启访问奖励与长期贡献回流。',
      researchValue: '科研价值',
      mintReady: '铸造就绪',
      pools: '科研池',
      totalGef: 'GEF 总量',
      returnWaterfall: '收益瀑布',
      returnTitle: '铸造后价值如何流动。',
      inventoryBoard: '待铸造资产清单',
      inventoryTitle: '可铸造的 Research NFT 数据包',
      viewArchive: '查看归档',
      enterVault: '进入金库',
      dataScope: '数据范围：',
      directions: '授权方向：',
      projectedValue: '预估价值',
      mintNow: '立即铸造',
      liveMatchbook: '实时匹配簿',
      matchbookTitle: '当前科研需求正在匹配你的资产。',
      refresh: '刷新',
      proofStream: '证明流运行中',
      proofTitle: '每次授权都有记录，每次回流都可追踪。',
      rewardStages: {
        mint: {
          name: '铸造奖励',
          value: '+18 GEF',
          detail: '当数据包被铸造为 Research NFT 并锚定到你的 DID 时触发。',
        },
        access: {
          name: '调用奖励',
          value: '+60 GEF',
          detail: '当科研方首次授权调用你的匿名资产时触发。',
        },
        contribution: {
          name: '贡献回流',
          value: '持续产生',
          detail: '由重复调用、阶段性研究或后续商业化回流触发。',
        },
      },
      packs: {
        metabolic: {
          title: '代谢连续性数据包',
          signals: 'CGM 180 天 · 餐食 · 睡眠恢复 · 家族史',
          directions: '2 型糖尿病早期干预、抗衰营养',
          status: '可铸造',
          value: '预计 260 GEF / 年',
        },
        cardio: {
          title: '心血管韧性数据包',
          signals: '血压 90 天 · HRV 6 个月 · 运动日志 · 血液标志物',
          directions: '高血压依从性、预防型保险模型',
          status: '再上传 1 项即可就绪',
          value: '预计 180 GEF / 年',
        },
      },
      matches: {
        glycemic: {
          title: '诺华 x MIT 血糖稳定性模型',
          reward: '100 GEF + 长期回流',
          action: '匿名授权',
        },
        longevity: {
          title: '日本长寿图谱队列',
          reward: '需补充基因型面板后解锁',
          action: '查看缺失指标',
        },
      },
      proofLogs: {
        did: '铸造时绑定 DID：did:gef:0x1a2b...3c4d',
        pools: '已授权科研池：代谢、长寿、心血管预防',
        calls: '12 次科研调用已记录链上贡献证明',
      },
      guidance: {
        mainTitle: '验证您的健康身份',
        mainDesc: '在开启科研铸造前，请先验证您的 ZK-DID 以确保所有权确权。',
        title: '什么是 Research NFT？',
        cta: '立即开启',
        step1: { title: '隐私加密', desc: '您的原始健康数据始终留在本地，确保隐私绝对安全。' },
        step2: { title: '身份确权', desc: '通过 ZK-Flare 协议将数据资产绑定到您的 DID。' },
        step3: { title: '价值回流', desc: '持有 R-NFT 参与科研，为您支付 GEF 奖励。' },
      },
      modal: {
        viewDetails: '查看明细',
        includedPoints: '包含的数据点',
        protocolReady: 'ZK-Flare 隐私保护协议已就绪',
        disclaimer: '铸造过程中，您的数据将通过零知识证明（ZKP）进行哈希处理。最终生成的 NFT 仅作为所有权凭证，不包含任何可识别的个人隐私。',
        confirmMint: '确认并前往铸造',
      },
      details: {
        hrv: { label: '心率变异性（HRV）', desc: '自主神经系统反馈（近 30 天）' },
        rhr: { label: '静息心率（RHR）', desc: 'BPM 趋势与基线' },
        sleep: { label: '睡眠结构', desc: '深睡、浅睡与 REM 睡眠比例' },
        metabolic: { label: '代谢效率', desc: '基于步数与热量消耗计算' },
        spo2: { label: '血氧饱和度（SpO2）', desc: '夜间血氧监测' },
        load: { label: '运动负荷', desc: '高强度运动期间的心肺表现' },
        recovery: { label: '恢复指数', desc: '运动后心率回落速度' },
      },
      accelerationTitle: '研究加速中心',
      accelerationDesc: '通过验证 DID 和分享数据，您可以将匹配效率提升 300%。',
      mintNFT: '铸造 Research NFT',
      reviewDID: '检查我的 DID',
      faq: {
        title: '了解更多科研知识',
        whatIs: {
          title: '什么是科研 NFT?',
          desc: '一个安全的加密容器，代表您在链上的结构化健康资产。'
        },
        privacy: {
          title: '隐私与安全',
          desc: '数据通过零知识证明 (ZK-Proofs) 匿名化。您的真实身份永远不会暴露。'
        },
        control: {
          title: '完全控制权',
          desc: '您可以随时撤销访问权限或删除资产。您拥有自己数据的私钥。'
        }
      },
    },
    profileShield: {
      title: '火焰盾',
      mutualAidProtocol: '互助保障协议',
      mutualAidDesc: '通过持续贡献 GEF，您将加入全球互助资金池。这一社区驱动的协议确保当任何成员面临重大健康挑战时，资金池的集体资源将提供全面的医疗和经济援助。',
      activeShieldStatus: '当前盾牌状态',
      goldTierSecurity: '黄金级保障',
      monthsActive: '活跃月数',
      totalCredit: '总信用',
      thisMonth: '本月',
      platformMatch: '平台匹配',
      progressToDiamond: '升级钻石进度',
      bronze: '青铜',
      silver: '白银',
      gold: '黄金',
      diamond: '钻石',
      legend: '传说',
      upgradeToDiamond: '升级到钻石需要',
      userLv5: '用户等级 5',
      guaranteedProtection: '保障服务',
      viewAll: '查看全部',
      japanesePrecisionCheck: '日本精密体检',
      stemCellStorage: '干细胞储存',
      prpTherapy: 'PRP 再生疗法',
      estimatedPrice1: '预估 ¥350,000-¥560,000',
      estimatedPrice2: '预估 ¥210,000-¥420,000',
      estimatedPrice3: '预估 ¥140,000-¥280,000',
      diamondExclusive: '升级到钻石盾以解锁这些服务',
      requiresLevel5: '需要用户等级 5',
      nkCell: 'NK 细胞免疫疗法 \u2014 20万-50万日元',
      protonTherapy: '质子/重离子治疗转介 — 40万-80万日元',
      howToUpgrade: '如何升级',
      upgradeShield: '升级盾牌',
      redemptionHistory: '兑换记录',
      planDetails: '方案详情',
    },
    shieldPage: {
      title: 'Flame Shield',
      vip: 'VIP',
      heroTitle: '高端准入，精英协同。',
      heroDesc: '你的健康资产贡献已解锁 Gold 等级，可获得日本等高端医疗资源的对接与协同权益。',
      currentTier: '当前等级',
      mutualPool: '互助池',
      benefitScore: '权益评分',
      unlocked: '已解锁',
      perks: '4 项权益',
      tierPathway: '等级路径',
      diamondProgress: '距 Diamond 72%',
      privilegeRunway: '权益跑道',
      runwayTitle: '贡献度与连续性共同解锁高端医疗权益。',
      privilegeServices: '权益服务',
      eliteDirectory: '高端医疗目录',
      required: '要求',
      paymentMethod: '支付方式',
      reserveAccess: '预约对接',
      locked: '未解锁',
      upgradeActions: {
        deposit: '向互助池再存入 48 GEF',
        authorize: '新增 1 个肿瘤级 Research NFT 授权',
        continuity: '保持 90 天穿戴与血液标志物数据连续性',
      },
      runwayPoints: {
        quality: '科研级数据质量会提升你的等级资格。',
        deposits: 'GEF 存入会扩大互助池，并提升权益上限。',
        review: 'AI 辅助审核提升协同效率，但不承诺医疗结果。',
      },
      services: {
        screening: {
          tier: 'Gold 3',
          title: '日本精密筛查协同',
          payment: '使用 GEF 或 Shield 积分支付',
          detail: '东京体检路径、双语病历准备与筛查后复盘支持。',
        },
        cart: {
          tier: 'Diamond',
          title: 'CAR-T 与质子治疗咨询',
          payment: 'GEF + SPARK 组合兑换',
          detail: '资格准备、跨境就医协同与专家二诊对接。',
        },
        regenerative: {
          tier: 'Legend',
          title: '再生医学礼宾服务',
          payment: 'Shield 等级优先准入',
          detail: '日本干细胞、抗衰老与高级恢复路径协同。',
        },
      },
    },
    profilePrivacy: {
      title: '隐私控制',
      desc: '控制您的健康数据如何被使用。您在链上拥有所有数据的完全所有权。',
      wearableData: '穿戴设备数据',
      wearableDesc: '心率、步数、睡眠、活动数据',
      physicalExam: '体检报告',
      physicalExamDesc: '血液检测、影像学检查、临床评估',
      questionnaireData: '问卷数据',
      questionnaireDesc: '健康调查、生活方式评估',
      geneticData: '基因数据',
      geneticDesc: '基因组分析、遗传标记',
      aiAnalysis: 'AI 分析',
      anonymousAggregate: '匿名聚合',
      tradeable: '可交易',
      globalMgmt: '全局管理',
      disableTrading: '禁用所有数据交易',
      disableAggregation: '禁用所有数据聚合',
      exportAll: '导出我的全部数据',
      deleteAccount: '删除账户与数据',
    },
    social: {
      searchPlaceholder: '搜索圈子、好友或动态...',
      dailyStar: '每日健康之星',
      joined: '已加入',
      hoursAgo: '{{count}} 小时前',
      insight: 'AI 康复建议',
      circles: '我的圈子',
      trending: '热门动态',
      tabs: {
        feed: '动态',
        circles: '圈子',
        challenges: '挑战',
        ranking: '排行榜'
      },
      aiRecommended: 'AI 推荐',
      precisionMatch: '精准匹配',
      cardioMgmt: '心血管管理',
      cardioMgmtDesc: '基于您最近的心率变异性和活动数据。',
      sleepOpt: '睡眠优化',
      sleepOptDesc: '加入 150+ 位通过集体数据改善 REM 周期的成员。',
      joinCircle: '加入圈子',
      browseMore: '浏览更多圈子',
      earlyBird: '早起挑战',
      earlyBirdDesc: '连续 21 天在早上 6:30 前起床',
      joinNow: '立即加入',
      popular: '热门挑战',
      springPrep: '春季马拉松备战',
      teamFatLoss: '团队减脂',
      stepsDaily: '每日一万步',
      hot: '热',
      team: '团队',
      seasonal: '季节性',
      comingSoon: '即将开始',
      summerHydration: '夏季饮水',
      mindfulnessMonth: '正念月',
      notifyMe: '提醒我',
      participants: '参与者',
      days: '天',
      starts: '开始时间',
      ranking: {
        steps: '步数',
        sleep: '睡眠',
        checkin: '签到',
        data: '数据',
        friends: '好友',
        circles: '圈子',
        global: '全球',
        thisWeek: '本周',
        leaderboard: '步数排行榜',
        rank: '排名',
        user: '用户',
        activity: '动态',
        viewAll: '查看所有参与者',
      },
    },
    settings: {
      title: '设置',
      account: '账号与安全',
      notifications: '通知设置',
      preferences: '偏好设置',
      language: '语言',
      langName: '简体中文',
      logout: '退出登录',
      identityBinding: '身份绑定',
      verified: '已验证',
      passwordPin: '密码与 PIN',
      biometricLogin: '生物识别登录',
      faceId: 'Face ID',
      walletSecurity: '钱包安全',
      healthReminders: '健康提醒',
      socialUpdates: '社交更新',
      promotions: '推广通知',
      darkMode: '深色模式',
      fontSize: '字体大小',
      medium: '标准',
      storageData: '存储与数据',
      clearCache: '清除缓存',
      appVersion: '应用版本',
      legal: '法律信息',
      termsOfService: '服务条款',
      privacyPolicy: '隐私政策',
      licenses: '开源许可',
    },
    quickActions: {
      title: '快捷操作',
      healthCheckin: '健康打卡',
      uploadReport: '上传报告',
      recordData: '记录数据',
      recordDiet: '记录饮食',
      medicationLog: '用药记录',
      fillQuestionnaire: '填写问卷',
      collapse: '收起',
      aiConsultation: 'AI 咨询',
      startDiagnostic: '开始专业诊断支持',
      pending: '待处理',
      pendingItems: '待处理项目',
    },
    ai: {
      closeTitle: '关闭对话',
      closeLabel: '关闭对话并返回',
      greeting: '您好！我是您的 GeneFlare AI 助手。我已经分析了您最新的生理年龄指标（目前为 28 岁）。今天有什么可以帮您的？',
      intro: '您可以让我解读医疗报告、制定个性化健康方案，或直接记录您的每日体征数据。',
      inputPlaceholder: '描述您的症状，或请求报告分析...',
      tapToUpload: '点击上传文件',
      checkinText: '我想进行每日健康打卡。',
      uploadText: '我有一份新的健康报告，可以帮我解读吗？',
      dataText: '我需要记录血压/血糖数据。',
      dietText: '记录今天的饮食。',
      medsText: '记录我的用药情况。',
      surveyText: '查看待填写的健康问卷。',
      respDefault: '正在为您处理。有什么特别需要我关注的地方吗？',
      respUpload: '明白。请上传您的报告（支持 PDF 或图片）。我将分析 12 个器官系统的指标，并生成生理年龄影响评估。',
      respCheckin: '好的，我们开始 60 秒健康打卡。您今天的精力水平如何？请用 1-10 分描述。',
      respData: '可以开始记录。您想记录血压、血糖还是心率？',
      respDiet: '我已打开您的饮食日记。您可以描述餐点，也可以拍照让我估算热量和营养结构。',
    },
    health: {
      title: '健康数据',
      tabs: {
        overview: '概览',
        data: '数据',
        assessment: '评估',
        plan: '方案',
        report: '报告',
      },
      twinTitle: '数字 Twin 可视化',
      integrity: '完整度',
      status: {
        normal: '正常',
        attention: '关注',
        risk: '风险',
      },
      coreMetrics: '核心指标',
      devices: {
        appleHealth: 'Apple Health',
        googleFit: 'Google Fit',
        geniusRing: '天才智能戒指',
        smartFabric: '智能织物',
      },
      manageMetrics: '管理指标',
      bp: '血压',
      sugar: '血糖',
      organScores: '器官系统评分',
      detailedAnalysis: '详细分析',
      radarLabel: {
        cardio: '心脏',
        resp: '呼吸',
        dig: '消化',
        meta: '代谢',
        musc: '肌肉',
        imm: '免疫',
      },
      radarLegend: {
        optimal: '优',
        attention: '良',
        risk: '风险',
        current: '当前活力值',
      },
      bioAge: {
        peak: '达到巅峰活力',
        age: '年龄',
        ageLabel: '您的生理年龄',
        desc: '您的表现相当于年轻 7 岁的人群水平，代谢效率处于较佳状态。',
      },
      alerts: 'AI 健康警示',
      viewAll: '查看全部',
      alertMetabolic: '代谢指标持续上升 3 个月',
      alertMetabolicDesc: '早期指标显示胰岛素敏感性正在发生变化。建议减少血糖波动。',
      alertSleep: '本周睡眠 HRV 偏低',
      alertSleepDesc: '恢复评分自周一以来下降了 15%。建议今晚优先保证充足的睡眠。',
      dataSources: '数据源',
      connected: '已连接',
      disconnected: '未连接',
      dataCompleteness: '数据完整度',
      healthTimeline: '健康数据时间线',
      loadMore: '加载更多...',
      assetCompleteness: {
        currentIntegrity: '当前完整度',
        heroDesc: '你的健康资产正在接近科研级密度。继续补全记录，即可解锁更高价值洞察。',
        manageAll: '管理全部',
        signalDensity: '信号密度拆解',
        aiAnalysis: 'AI 信号分析',
        mintResearchNFT: '铸造 Research NFT',
        addSource: '添加数据源',
        sourceDesc: {
          dailySync: '每日同步已开启',
          ready: '可用于分析',
          connect: '点击连接',
        },
        timeline: {
          autoSync: '自动同步',
          autoSyncDetail: '心率 72 · 步数 3,240',
          sleepData: '睡眠数据',
          sleepDataDetail: '时长 7 小时 12 分 · 深睡 1 小时 45 分',
          manualEntry: '手动记录',
          manualEntryDetail: '血压 118/76',
          uploadedReport: '上传体检报告',
          uploadedReportDetail: 'AI 分析完成',
          questionnaire: '季度健康问卷',
          questionnaireDetail: '已完成',
          today: '今天 10:32',
          yesterday: '昨天 22:15',
          mar28: '3月28日',
          mar25: '3月25日',
          mar15: '3月15日',
        },
      },
      tags: {
        wearable: '穿戴数据',
        questionnaire: '调查问卷',
        physicalExam: '体检报告',
        medLog: '用药记录',
        genetics: '基因检测',
        diet: '饮食日记',
      },
      medicationAd: '完善用药记录以解锁由 GeneFlare AI 驱动的高级药物相互作用分析。',
      riskFactors: '我的健康风险因素',
      analysisDate: '分析时间: 10月8日',
      highRisk: '高风险',
      caution: '关注',
      lowRisk: '低风险',
      fbs: '空腹血糖',
      fbsDesc: '检测到血糖水平升高，建议立即进行临床复查。',
      sleepHRV: '睡眠 HRV',
      bmiOverweight: 'BMI 超重',
      vitD: '维生素 D',
      vitDDesc: '保持充足的水平',
      availableAssessments: '可用评估',
      aiReady: 'AI 引擎已就绪',
      assessProfile: '综合概况',
      assessProfileDesc: '全面分子和基因组扫描',
      assessCardio: '心血管风险',
      assessCardioDesc: '动脉年龄和血脂评估',
      assessMeta: '代谢健康',
      assessMetaDesc: '血糖反应与胰岛素',
      assessBioAge: '生理年龄',
      assessBioAgeDesc: '表观遗传时钟分析',
      estResult: '预计48小时出结果',
      realtimeSync: '实时同步',
      historicalReports: '历史报告',
      digitalTwinInfo: '在区块链上生成您的生物学预测 AI 模型。',
      initiateSync: '开始同步',
      activePlans: '正在进行的计划',
      targetRisks: '针对风险',
      healthBenefits: '健康益处',
      aiRecPlan: 'AI 推荐计划',
      aiRecBody: '基于您最近的 HRV 数据，建议进行正念与呼吸训练以降低晚间压力。',
      reviewProtocol: '查看方案',
      effectTracking: '效果追踪',
      restingHR: '静息心率',
      dailySteps: '每日步数',
      deepSleep: '深度睡眠',
      completedPlans: '已完成的计划',
      monthlyReport: '月度报告',
      compReview: '全面回顾',
      examAnalysis: '体检分析',
      bioDetected: '检测到 12 项生物标志物',
      precisionAI: '精准 AI 评估',
      stabilityIndex: '稳定性指数: 98%',
      mintTitle: '铸造健康数据 NFT',
      mintDesc: '将您的健康报告安全记录在链上，并赚取主权奖励。',
      mintReq: '需要等级 4+',
      unlockMint: '解锁铸造功能',
      aiGenerated: 'AI 生成',
      verified: '已验证',
      lowRiskBadge: '低风险',
    },
    healthPlan: {
      dashboard: {
        pageTitle: '全部计划',
        tag: '计划看板',
        title: '把每个任务归入清晰的健康计划。',
        desc: '个人健康计划、机构计划和所有关联任务都汇入同一个看板。你可以看到正在执行、推荐加入，以及值得关注的机构计划。',
        executingPlans: '执行中计划',
        todayTasks: '今日任务',
        recommendedPlans: '推荐计划',
        institutionPlans: '机构计划',
      },
      executing: '执行中的计划',
      recommended: '推荐加入的计划',
      institution: '机构研究计划',
      effectTracking: '效果追踪',
      completed: '已完成的计划',
      activeNow: '正在执行',
      researchLinked: '关联科研',
      taskStates: '任务状态',
      planQueue: '计划任务队列',
      mixedStatus: '多种状态',
      planValue: '计划价值',
      todayTask: '今日任务',
      reward: '计划奖励',
      completedPlansMap: {
        'hydration-challenge': '饮水连续挑战',
        'intermittent-fasting-intro': '间歇性禁食入门',
      },
    },
    healthScorePage: {
      title: '健康评估',
      overallScore: '综合健康评分',
      gradeLabel: '高于平均 · 优秀',
      scoreDesc: '您的整体健康状况良好。1 个高风险因素和 2 个关注项需要注意。',
      riskEntry: '健康风险因素',
      poor: '差',
      fair: '一般',
      good: '良好',
      excellent: '优秀',
    },
    shieldLayout: {
      tabsLabel: '权益导航',
      home: 'Shield 首页',
      services: '服务',
    },
    shieldServices: {
      premium: '高端服务',
      title: '全球医疗\n资源网络。',
      desc: '为 Flame Shield 成员精选高端医疗准入与长寿管理服务。',
      payment: '支付方式',
      services: {
        jpCheckup: {
          title: '日本精密体检套餐',
          category: '诊断筛查',
          payment: '使用 GEF 或 Shield 积分支付',
          detail: '高分辨率影像、综合血液标志物、双语翻译支持，以及东京顶级临床团队的随访复盘。',
          tags: {
            petct: 'PET-CT',
            biomarkers: '生物标志物',
            vipRouting: 'VIP 通道',
          },
        },
        longevity: {
          title: '长寿干预规划',
          category: '再生医学',
          payment: 'GEF + SPARK 组合兑换',
          detail: '抗衰管理、表观遗传标志物复盘，以及面向细胞优化的高端诊所协同。',
          tags: {
            antiAging: '抗衰',
            stemCell: '干细胞',
            coaching: '健康管理',
          },
        },
        referral: {
          title: '跨境专家转诊',
          category: '专家咨询',
          payment: 'Shield 等级优先准入',
          detail: '针对肿瘤、罕见病和先进疗法，对接全球知名专家二诊与快速通道。',
          tags: {
            oncology: '肿瘤',
            secondOpinion: '专家二诊',
            fastTrack: '快速通道',
          },
        },
      },
    },
    collectionPage: {
      title: '数据金库',
      tag: '安全资产仓库',
      heading: '我的收藏',
      vaultNetWorth: '金库净值',
      annualApr: '年化 APR',
      tier: '等级',
      active: '运行中',
      totalYield: '累计收益',
      integrity: '完整度',
      assets: {
        metabolic: '代谢矩阵',
        cardio: '心血管节律',
        neuro: '神经模式',
      },
    },
    plansData: {
      'sleep-repair-protocol': {
        sourceLabel: '个人健康方案',
        progressLabel: '第 6 / 14 天',
        summary: '重建夜间恢复稳定性，并为 Shield 审核生成更清晰的疲劳风险历史。',
        recommendationReason: '你近期睡眠连续性低于目标，因此该方案具备最高的近期提升价值。',
        todayAction: '今晚 22:30 前开启睡眠窗口。',
        planValue: '睡眠恢复证明 +1',
      },
      'cardio-recovery-loop': {
        sourceLabel: '个人健康方案',
        progressLabel: '3 项任务进行中',
        summary: '把血管恢复、运动节律和补水行为纳入同一个稳定周循环。',
        recommendationReason: '你的步数与心率数据已经足够支撑该连续性计划。',
        todayAction: '验证最近 5 次快走记录。',
        planValue: '恢复连续性 +18',
      },
      'institution-metabolic-reset': {
        sourceLabel: '诺华代谢实验室',
        progressLabel: '开放加入',
        summary: '由研究机构支持的代谢重置计划，围绕血糖连续性、营养时机与干预准备度展开。',
        recommendationReason: '你的血糖上传与营养日志已经匹配 68% 的基础要求。',
        todayAction: '上传最近 7 天连续血糖读数。',
        planValue: '科研准入 +1',
        participants: '240 个名额',
        duration: '14 天',
        progress: '基线匹配 68%',
        tag: 'AI 推荐',
      },
      'tokyo-longevity-observation': {
        sourceLabel: '东京精密健康网络',
        progressLabel: '剩余 2 个队列',
        summary: '与日本资源关联的观察计划，关注睡眠、穿戴连续性和长寿生物标志物配对。',
        recommendationReason: '你当前睡眠与恢复历史适合进入下一批观察窗口。',
        todayAction: '绑定 14 天穿戴连续性与空腹标志物摘要。',
        planValue: '日本队列评审',
        participants: '128 个名额',
        duration: '21 天',
        progress: '队列开放',
        tag: '日本队列',
      },
      'bayer-vascular-signal-study': {
        sourceLabel: '拜耳研究中心',
        progressLabel: '招募中',
        summary: '面向长期信号采集的血压与血管依从性结构化计划。',
        recommendationReason: '你的血压历史已接近铸造级，完成该计划可进一步升级。',
        todayAction: '记录 30 天血压序列。',
        planValue: '血管信号包',
        participants: '180 个名额',
        duration: '30 天',
        progress: '信号采集',
        tag: '铸造关联',
      },
    },
    profilePage: {
      controlCenter: '控制中心',
      title: '你的 Web3 健康身份',
      desc: '这是你的 Research NFT 资产与 Flame Shield 权益的加密核心。掌握数据主权，安全调度访问。',
      primaryDid: '主 DID',
      nodeRouting: '节点路由',
      singaporeNode: '新加坡全球节点',
      behaviorRewards: '行为奖励',
      thisWeek: '本周 +450',
      settlementShield: '结算与护盾',
      gefDesc: '用于 Shield 升级的核心治理代币。',
      stakeGef: '质押 GEF',
      rToken: 'R-Token',
      activeProjects: '3 个项目',
      activeProjectsDesc: '当前生效中的专项科研权限。',
      authorizationCenter: '授权中心',
      authorizationDesc: '管理 4 项活跃科研授权，关闭广告用途，并导出你的授权日志。',
      privacy: '隐私',
      privacyDesc: '调整科研权限并导出数据账本。',
      preferences: '偏好',
      preferencesDesc: '安全、语言、通知与钱包设置。',
      researchAssets: '科研资产',
      dataVault: '数据金库',
      dataVaultDesc: '查看你已验证健康 NFT 的收藏与收益记录。',
    },
    mintWorkflow: {
      scanning: "正在扫描信号",
      scanningDetail: "汇总生物特征数据...",
      encrypting: "DID 加密处理",
      encryptingDetail: "正在生成零知识证明保护...",
      finalizing: "正在上链存证",
      finalizingDetail: "提交至科研数据账本...",
      success: "铸造成功",
      successDetail: "您的健康资产已激活，正在产生科研收益。",
      inventory: "查看我的库存",
      metadata: {
        authenticated: "已验证资产",
        integrity: "数据完整度",
        reward: "收益池等级",
        disclaimer: "此证书证明生物识别数据已通过 ZK-Flare 协议处理，并已正式提交至分布式科研账本。"
      }
    }
  }
};

const LanguageContext = createContext();
const LANGUAGE_STORAGE_KEY = 'geneflare_lang';
const LEGACY_LANGUAGE_STORAGE_KEY = ['mio', 'health', 'lang'].join('_');

export function LanguageProvider({ children }) {
  const [lang, setLangState] = useState(() => {
    const savedLang = localStorage.getItem(LANGUAGE_STORAGE_KEY);
    if (savedLang) return savedLang;

    const legacyLang = localStorage.getItem(LEGACY_LANGUAGE_STORAGE_KEY);
    if (legacyLang) {
      localStorage.setItem(LANGUAGE_STORAGE_KEY, legacyLang);
      return legacyLang;
    }

    return 'zh';
  });

  const setLang = (newLang) => {
    setLangState(newLang);
    localStorage.setItem(LANGUAGE_STORAGE_KEY, newLang);
  };

  const t = (path, params = {}) => {
    const keys = path.split('.');
    let result = translations[lang];
    for (const key of keys) {
      if (result && result[key]) {
        result = result[key];
      } else {
        let fallback = translations.en;
        for (const fallbackKey of keys) {
          if (fallback && fallback[fallbackKey]) {
            fallback = fallback[fallbackKey];
          } else {
            return path;
          }
        }
        result = fallback;
        break;
      }
    }
    if (typeof result !== 'string') {
      return result ?? path;
    }
    return result.replace(/{{(\w+)}}/g, (_, key) => params[key] ?? '');
  };

  const toggleLanguage = () => {
    const newLang = lang === 'en' ? 'zh' : 'en';
    setLang(newLang);
  };

  return (
    <LanguageContext.Provider value={{ lang, t, setLang, toggleLanguage }}>
      {children}
    </LanguageContext.Provider>
  );
}

export const useLanguage = () => useContext(LanguageContext);
